name: adaptive-infra-env
channels:
    - defaults
    - conda-forge
dependencies:
    - python
    - pip
    - numpy
    - pandas
    - geopandas
    - scipy
    - scikit-learn
    - xgboost
    - ipykernel
    - notebook
    - matplotlib
    - pip:
        - shap
        - haversine
