name: iecdt2
channels:
    - defaults
    - conda-forge
dependencies:
    - python
    - pip
    - numpy
    - pandas
    - geopandas # ==0.14.4
    # - fiona==1.10.0 # https://stackoverflow.com/questions/78949093/how-to-resolve-attributeerror-module-fiona-has-no-attribute-path
    - scipy
    - scikit-learn #Â https://stackoverflow.com/questions/68620927/installing-scipy-and-scikit-learn-on-apple-m1
    - py-xgboost
    # - shap         # use pip on M1 macs "python -m pip install shap"
    - ipykernel
    - notebook
    - matplotlib
    - pip:
        - shap
        # - haversine
